### ISSUE TITLE
Multiquote cookie is not removed when quoting

### ISSUE THREAD

**Issue by zefciu** [ateista-pl/forum#1]
Browser: Firefox
Editor used: plaintext

When I check several posts to multiquote them and then click 'answer', it correctly allows me to multiquote, but after that the cookie is not removed. This way I quote all these posts every time I try to answer in that thread. I can help  this by removing the 'multiquote' cookie manually, but it should be removed by the script when I open the editor.

**Comment by fizyk20** [comment]
Działa, choć w sumie nie wiadomo czemu ;)
